#!/usr/bin/env ruby

# Program Listing
# THIS PROGRAM PITS TWO DESTROYERS AGAINST EACH OTHER 3D
# ONE VESSEL IS UNDER YOUR COMMAND  THE OTHER IS UNDER COMPUTER  CONTROL SO
# TO EVEN THE ODDS, THE COMPUTER MUST USE RANDOM VARIABLES OR ELSE THE CONTEST
# WOULD DEFINITELY BE BIASED TOWARDS THE COMPUTER.
# ESTABLISH DISTANCE AT START OF GAME
D = 1000 + INT - CRND - CO * 5000
# ESTABLISH NUMBER OF SHOTS AVAILABLE
# TO THE ENEMY

require 'game'

g = new Game()
g.loop
